---
# tasks file for amok_exifsorter
- name: Install Block
  block:
    - name: Create Amok-Exifsorter download dir on remote host if it does not exist
      become: true
      become_user: "{{ ansible_user }}"
      ansible.builtin.file:
        path: "{{ download_dir_on_remote_host }}/amok_exifsorter"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Download installer
      become: true
      become_user: "{{ ansible_user }}"
      ansible.builtin.get_url:
        url: "https://www.amok.am/files/releases/exifsorter-{{ amok_exifsorter.version }}.tar.bz2"
        dest: "{{ download_dir_on_remote_host }}/amok_exifsorter/exifsorter-{{ amok_exifsorter.version }}.tar.bz2"
        checksum: "{{ amok_exifsorter.checksum }}"
        timeout: 60
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      register: amok_exifsorter_installer

    - name: Clean destination folder if needed
      become: true
      ansible.builtin.file:
        path: "/opt/amok_exifsorter"
        state: absent
      when: amok_exifsorter_installer.changed

    - name: Create destination folder if needed
      become: true
      ansible.builtin.file:
        path: "/opt/amok_exifsorter"
        state: directory
        owner: "root"
        group: "root"
        mode: '0755'
      when: amok_exifsorter_installer.changed

    - name: Install in dir
      become: true
      ansible.builtin.unarchive:
        src: "{{ download_dir_on_remote_host }}/amok_exifsorter/exifsorter-{{ amok_exifsorter.version }}.tar.bz2"
        dest: "/opt/amok_exifsorter"
        remote_src: true
      when: amok_exifsorter_installer.changed

    - name: Menu-Entry for all users
      become: true
      ansible.builtin.template:
        src: "amok_exifsorter.desktop.j2"
        dest: "/usr/share/applications/amok_exifsorter.desktop"
        owner: "root"
        group: "root"
        mode: '0644'
