---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    ansible_user: "root"

    - name: Testing role
      ansible.builtin.include_role:
        name: jakoblichterfeld.amok_exifsorter
