---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Instance
    image: "ubuntu:latest"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
